development:
  adapter: mysql2
  database: change_to_spare_development
  user: root
  password:
  host: localhost
  pool: 5
  timeout: 5000

test:
    adapter: mysql2
    database: change_to_spare_test
    user: root
    password:
    host: localhost
    pool: 5
    timeout: 5000

production:
  adapter: mysql2
  database: change_to_spare_production
  user: root
  password:
  host: localhost
  pool: 5
  timeout: 5000